apiVersion: v1
kind: Service
metadata:
  name: {{ include "babylonCatalog.oauthProxyName" . }}
  namespace: {{ include "babylonCatalog.namespaceName" . }}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: {{ printf "%s-tls" (include "babylonCatalog.oauthProxyName" .) }}
  labels:
    {{- include "babylonCatalog.labels" . | nindent 4 }}
spec:
  ports:
  - name: proxy
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    {{- include "babylonCatalog.oauthProxySelectorLabels" . | nindent 4 }}
  type: ClusterIP
