---
gunicorn:
  processes: 5
  threads: 1

image:
  #override:
  repository: quay.io/redhat-cop/babylon-catalog
  pullPolicy: IfNotPresent

imagePullSecrets: []

namespace:
  create: true
  name:

nameOverride: ""

replicaCount: 1

resources:
  requests:
    cpu: 500m
    memory: "2Gi"
  limits:
    cpu: "2"
    memory: "2Gi"

serviceAccount:
  name: # default use chart name

oauthProxy:
  cookieSecret: SECRET
  image: openshift/oauth-proxy:latest

redis:
  name: # default use chart name + '-redis'
  deploy: true
  password:
  generatePassword: true
  image: image-registry.openshift-image-registry.svc:5000/openshift/redis:5-el8
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 256Mi
