{{- if (or .Values.redis.password .Values.redis.generatePassword) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "babylonCatalog.redisName" . }}
  namespace: {{ include "babylonCatalog.namespaceName" . }}
  labels:
    {{- include "babylonCatalog.labels" . | nindent 4 }}
data:
  {{- if .Values.redis.password }}
  database-password: {{ .Values.redis.password | b64enc }}
  {{- else }}
  database-password: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
{{- end }}
