apiVersion: v1
kind: Service
metadata:
  name: {{ include "babylonCatalog.redisName" . }}
  namespace: {{ include "babylonCatalog.namespaceName" . }}
  labels:
    {{- include "babylonCatalog.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    {{- include "babylonCatalog.redisSelectorLabels" . | nindent 4 }}
