apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rhpds
  namespace: babylon
spec:
  dnsNames:
  - rhpds.apps-dev.open.redhat.com
  duration: 2160h0m0s
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 360h0m0s
  secretName: rhpds-tls
  uris:
  - spiffe://cluster.local/ns/cert-manager-test/sa/default
  usages:
  - server auth
