apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "babylonCatalog.clusterRoleName" . }}
  labels:
    {{- include "babylonCatalog.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  - user.openshift.io
  resources:
  - groups
  - users
  verbs:
  - get
  - impersonate
  - list
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
