apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "babylonCatalog.name" . }}
  namespace: {{ include "babylonCatalog.namespaceName" . }}
  labels:
    {{- include "babylonCatalog.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "babylonCatalog.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "babylonCatalog.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "babylonCatalog.serviceAccountName" . }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: proxy-tls
        secret:
          defaultMode: 0644
          secretName: {{ printf "%s-tls" (include "babylonCatalog.name" .) }}
      containers:
      - name: app
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "babylonCatalog.redisName" . }}
              key: database-password
        - name: REDIS_SERVER
          value: {{ include "babylonCatalog.redisName" . }}
        - name: REDIS_PORT
          value: "6379"
        - name: GUNICORN_PROCESSES
          value: "{{ .Values.gunicorn.processes }}"
        - name: GUNICORN_THREADS
          value: "{{ .Values.gunicorn.threads }}"
        image: {{ include "babylonCatalog.image" . | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          initialDelaySeconds: 30
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      - name: oauth-proxy
        args:
        - --https-address=:8443
        - --provider=openshift
        - {{ (printf "--openshift-service-account=%s" (include "babylonCatalog.name" .)) | quote }}
        - --upstream=http://localhost:8080
        - --tls-cert=/etc/tls/private/tls.crt
        - --tls-key=/etc/tls/private/tls.key
        - {{ (printf "--cookie-secret=%s" .Values.oauthProxy.cookieSecret) | quote }}
        image: {{ .Values.oauthProxy.image | quote }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
          name: public
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /etc/tls/private
          name: proxy-tls
