apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "babylonCatalog.name" . }}
  namespace: {{ include "babylonCatalog.namespaceName" . }}
  labels:
    {{- include "babylonCatalog.labels" . | nindent 4 }}
spec:
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: {{ include "babylonCatalog.name" . }}
