apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "babylonCatalog.name" . }}
  namespace: {{ include "babylonCatalog.namespaceName" . }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: >-
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":{{ (include "babylonCatalog.name" .) | quote }}}}
  labels:
    {{- include "babylonCatalog.labels" . | nindent 4 }}
