apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-access" (include "babylonCatalog.name" .) }}
  labels:
    {{- include "babylonCatalog.labels" . | nindent 4 }}
rules:
- apiGroups:
  - babylon.gpte.redhat.com
  resources:
  - catalogitems
  verbs:
  - get
  - list
  - watch
