apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "babylonCatalog.apiName" . }}
  namespace: {{ include "babylonCatalog.namespaceName" . }}
  labels:
    {{- include "babylonCatalog.labels" . | nindent 4 }}
