apiVersion: v1
kind: Service
metadata:
  name: {{ include "babylonCatalog.apiName" . }}
  namespace: {{ include "babylonCatalog.namespaceName" . }}
  labels:
    {{- include "babylonCatalog.labels" . | nindent 4 }}
spec:
  ports:
  - name: api
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    {{- include "babylonCatalog.apiSelectorLabels" . | nindent 4 }}
  type: ClusterIP
