{{ if .Values.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "babylon-lab-ui-manager.name" . }}
  namespace: {{ include "babylon-lab-ui-manager.namespaceName" . }}
  labels:
    {{- include "babylon-lab-ui-manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "babylon-lab-ui-manager.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "babylon-lab-ui-manager.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: lab-ui-manager
        image: {{ include "babylon-lab-ui-manager.image" . | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        livenessProbe:
          initialDelaySeconds: 30
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      serviceAccountName: {{ include "babylon-lab-ui-manager.serviceAccountName" . }}
      terminationGracePeriodSeconds: 30
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
