{{ if .Values.deploy }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "babylon-lab-ui-manager.serviceAccountName" . }}
  namespace: {{ include "babylon-lab-ui-manager.namespaceName" . }}
  labels:
    {{- include "babylon-lab-ui-manager.labels" . | nindent 4 }}
{{ end }}
