apiVersion: poolboy.gpte.redhat.com/v1
kind: ResourceProvider
metadata:
  name: tests.babylon-empty-config.dev
  namespace: poolboy
spec:
  override:
    apiVersion: anarchy.gpte.redhat.com/v1
    kind: AnarchySubject
    metadata:
      namespace: anarchy-operator
      generateName: tests.babylon-empty-config.dev-
    spec:
      governor: tests.babylon-empty-config.dev
      vars:
        babylon_user_email: >-
          {{: requester_identity.extra.email | default(None) if requester_identity else None :}}
        babylon_user_fullname: >-
          {{: requester_identity.extra.name | default(None) if requester_identity else None :}}
        babylon_username: >-
          {{: requester_user.metadata.name | default(None) if requester_user else None :}}
        healthy: true
        job_vars:
          guid: >-
            {{: resource_handle.metadata.name[5:] if resource_handle.metadata.name.startswith('guid-') else resource_handle.metadata.name :}}
  updateFilters:
  - pathMatch: /spec/vars/desired_state
  validation:
    openAPIV3Schema:
      additionalProperties: false
      required:
      - spec
      properties:
        spec:
          type: object
          required:
          - vars
          additionalProperties: false
          properties:
            vars:
              type: object
              additionalProperties: false
              properties:
                desired_state:
                  description: >-
                    Set to "stopped" to immediately stop the environment after provision.
                  x-formLabel: Desired State
                  x-formOrder: 9999
                  type: string
                  default: started
                  enum:
                  - started
                  - stopped
                job_vars:
                  type: object
                  additionalProperties: false
                  properties:
                    fail_infra:
                      description: Set to true to have agnosticd fail in infra.yml
                      default: false
                      type: boolean
                      x-formLabel: Fail in AgnosticD infra
                      x-formOrder: 20
                    fail_post_infra:
                      default: false
                      description: Set to true to have agnosticd fail in post_infra.yml
                      type: boolean
                      x-formLabel: Fail in AgnosticD post-infra
                      x-formOrder: 30
                    fail_post_software:
                      default: false
                      description: Set to true to have agnosticd fail in post_software.yml
                      type: boolean
                      x-formLabel: Fail in AgnosticD post-software
                      x-formOrder: 60
                    fail_pre_infra:
                      default: false
                      description: Set to true to have agnosticd fail in pre_infra.yml
                      type: boolean
                      x-formLabel: Fail in AgnosticD pre-infra
                      x-formOrder: 10
                    fail_pre_software:
                      default: false
                      description: Set to true to have agnosticd fail in pre_software.yml
                      type: boolean
                      x-formLabel: Fail in AgnosticD pre-software
                      x-formOrder: 40
                    fail_software:
                      default: false
                      description: Set to true to have agnosticd fail in software.yml
                      type: boolean
                      x-formLabel: Fail in AgnosticD software
                      x-formOrder: 50
                    test_empty_config_pause_post_software:
                      default: false
                      description: Set to numeric value to control duration of pause during post_software.yml
                      type: boolean
                      x-formLabel: Pause in AgnosticD post-software
                      x-formOrder: 100
                    test_empty_config_pause_post_software_seconds:
                      default: 30
                      type: integer
                      x-formDependsOn: test_empty_config_pause_post_software
                      x-formLabel: Pause in AgnosticD post-software
                      x-formOrder: 110
